version: '3.1'

services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app

  db:
    image: 'postgres:10.4-alpine'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.development

  #redis:
    #image: 'redis:4.0-alpine'
    #command: ["redis-server", "--appendonly", "yes"]
    #volumes:
      #- ./redis-data:/data
